"""
==============================================================================
YOTCHAPPS PAYROLL ENGINE - APPLICATION FACTORY & SECURITY PERIMETER
==============================================================================
This module serves as the primary initialization sequence for the Flask application.
It strictly enforces the Application Factory Pattern, ensuring that the app is 
instantiated dynamically. This allows for clean testing environments and isolates 
the security configurations from the core routing logic.

Core Responsibilities:
1. Reverse Proxy Resolution: Safely extracts the true client IP behind Cloud Run.
2. The Memory Defense: Implements a strict payload kill-switch to prevent OOM attacks.
3. The Middleware Injection: Hooks Flask-WTF (CSRF) and Flask-Limiter into the app.
4. The Header Matrix: Forces strict HTTP security headers (CSP, No-Sniff, No-Cache).
5. The Blueprint Registry: Mounts the main routing logic to the application.
==============================================================================
"""

import os
from flask import Flask
from werkzeug.middleware.proxy_fix import ProxyFix
from .extensions import csrf, limiter

def create_app():
    """
    Constructs, configures, and secures the Flask WSGI application instance.
    """
    app = Flask(__name__)
    
    # ==========================================
    # LAYER 1: REVERSE PROXY IP RESOLUTION
    # ==========================================
    # When deployed to Google Cloud Run, the app sits behind Google's Global Load 
    # Balancers. Without this fix, Flask-Limiter would see every request coming 
    # from the same internal Google IP (e.g., 127.0.0.1) and instantly ban everyone.
    # ProxyFix tells Werkzeug to trust the 'X-Forwarded-For' headers securely.
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)

    # ==========================================
    # LAYER 2: MEMORY & CRYPTOGRAPHIC DEFENSE
    # ==========================================
    # Fetches the randomized 256-bit key generated by deploy.sh for CSRF signing.
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'fallback-dev-key-only')
    
    # THE FAT PAYLOAD KILL-SWITCH
    # Prevents malicious actors from sending a 500MB JSON payload to crash the container.
    # Flask will instantly sever the connection if the body exceeds 50 Kilobytes.
    app.config['MAX_CONTENT_LENGTH'] = 50 * 1024  

    # Inject the configured extensions into the app instance
    csrf.init_app(app)
    limiter.init_app(app)

    # ==========================================
    # LAYER 3: STRICT BROWSER DEFENSES (HTTP HEADERS)
    # ==========================================
    @app.after_request
    def add_security_headers(response):
        """
        Intercepts every outbound HTTP response and violently enforces 
        modern browser security protocols before it reaches the client.
        """
        # Prevents browsers from guessing the MIME type (stops MIME-sniffing XSS attacks)
        response.headers['X-Content-Type-Options'] = 'nosniff'
        
        # Prevents Clickjacking by forbidding the app from being embedded in an iframe
        response.headers['X-Frame-Options'] = 'DENY'
        
        # Financial Data Protection: Forces the browser to NEVER cache the mathematical 
        # results or the JSON payload in the user's local hard drive history.
        response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
        
        # THE TITANIUM UPGRADE: Content Security Policy (CSP)
        # This is the ultimate defense against Cross-Site Scripting (XSS).
        # It strictly commands the browser to ONLY execute scripts and load styles 
        # from explicitly whitelisted domains (Our App, Cloudflare, Google Fonts, jsDelivr).
        # If an attacker injects a malicious script, the browser will refuse to run it.
        csp = (
            "default-src 'self'; "
            "script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; "
            "style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://cdn.jsdelivr.net; "
            "font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; "
            "img-src 'self' data:; "
            "connect-src 'self' https://cdnjs.cloudflare.com;" # Required for MDB debugging maps
        )
        response.headers['Content-Security-Policy'] = csp
        
        return response

    # ==========================================
    # LAYER 4: GRACEFUL RATE LIMIT HANDLING
    # ==========================================
    @app.errorhandler(429)
    def ratelimit_handler(e):
        """
        Catches API spam attempts (e.g., hitting /api/calculate 30+ times a minute)
        and returns a clean, sanitized JSON error instead of an ugly HTML stack trace.
        """
        return {"error": "Rate limit exceeded. Please wait a moment before recalculating."}, 429

    # ==========================================
    # LAYER 5: BLUEPRINT REGISTRY
    # ==========================================
    # Mounts the isolated routing logic (main.py) to the core application factory.
    from .main import main_bp
    app.register_blueprint(main_bp)

    return app