"""
==============================================================================
YOTCHAPPS PAYROLL ENGINE - EXTENSIONS REGISTRY
==============================================================================
This module isolates the instantiation of Flask extensions from the main 
application factory. This prevents circular import dependencies and allows 
for seamless unit testing.

Security Plugins:
1. CSRFProtect: Cryptographically signs forms and POST requests to prevent 
   Cross-Site Request Forgery attacks.
2. Limiter: An in-memory rate limiter that tracks clients by their true IP 
   address to prevent DDoS attacks, API spam, and automated scraping.
==============================================================================
"""

from flask_wtf.csrf import CSRFProtect
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

# ==========================================
# 1. CSRF PROTECTION (Cross-Site Request Forgery)
# ==========================================
# Enforces a strict requirement that all state-changing requests (POST, PUT, DELETE)
# contain a valid, secret-signed token generated by the server. 
csrf = CSRFProtect()

# ==========================================
# 2. GLOBAL RATE LIMITER (DDoS Defense)
# ==========================================
# Tied strictly to the user's Remote Address (IP). Because the application uses 
# Werkzeug's ProxyFix in __init__.py, get_remote_address safely bypasses Google 
# Cloud Run's internal load balancers to ban the attacker's actual origin IP.
limiter = Limiter(key_func=get_remote_address)